spring:
  data:
    mongodb:
      uri: mongodb+srv://asifdada172:k7K4gFx9w72niqac@cluster0.edoc9fy.mongodb.net/mighty_groups_db?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8080

app:
  jwtSecret: 1a2b3c4d5e6f7g8h9i10j11k12l13m14n15o16p17q18r19s20t21u22v23w24x25y26z  # 64+ characters
  jwtExpirationInMs: 86400000
